version: 2

sources:
  - name: staging
    database: kestra-sandbox-455814
    schema: kestra

    tables:
      - name: green_tripdata
      - name: yellow_tripdata

models:
  - name: stg_yellow_tripdata
    description: ""
    columns:
      - name: trip_id
        data_type: string
        description: ""

      - name: filename
        data_type: string
        description: ""

      - name: vendorid
        data_type: int64
        description: ""

      - name: ratecodeid
        data_type: int64
        description: ""

      - name: pickup_location_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('dim_zones')
              field: location_id
              severity: warn

      - name: dropoff_location_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('dim_zones')
              field: location_id
              severity: warn

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: store_and_fwd_flag
        data_type: string
        description: ""

      - name: passenger_count
        data_type: int64
        description: ""

      - name: trip_distance
        data_type: numeric
        description: ""

      - name: trip_type
        data_type: int64
        description: ""

      - name: fare_amount
        data_type: numeric
        description: ""

      - name: extra
        data_type: numeric
        description: ""

      - name: mta_tax
        data_type: numeric
        description: ""

      - name: tip_amount
        data_type: numeric
        description: ""

      - name: tolls_amount
        data_type: numeric
        description: ""

      - name: ehail_fee
        data_type: numeric
        description: ""

      - name: improvement_surcharge
        data_type: numeric
        description: ""

      - name: total_amount
        data_type: numeric
        description: ""

      - name: payment_type
        data_type: int64
        description: ""
        tests:
          - accepted_values:
              values: "{{ var('payment_type_values') }}"
              severity: warn
              quote: false # so that the values inside array won't be interpreted as a string

      - name: payment_type_description
        data_type: string
        description: ""

  - name: stg_green_tripdata
    description: ""
    columns:
      - name: trip_id
        data_type: string
        description: ""

      - name: filename
        data_type: string
        description: ""

      - name: vendorid
        data_type: int64
        description: ""

      - name: ratecodeid
        data_type: int64
        description: ""

      - name: pickup_location_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('dim_zones')
              field: location_id
              severity: warn

      - name: dropoff_location_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('dim_zones')
              field: location_id
              severity: warn

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: store_and_fwd_flag
        data_type: string
        description: ""

      - name: passenger_count
        data_type: int64
        description: ""

      - name: trip_distance
        data_type: numeric
        description: ""

      - name: trip_type
        data_type: int64
        description: ""

      - name: fare_amount
        data_type: numeric
        description: ""

      - name: extra
        data_type: numeric
        description: ""

      - name: mta_tax
        data_type: numeric
        description: ""

      - name: tip_amount
        data_type: numeric
        description: ""

      - name: tolls_amount
        data_type: numeric
        description: ""

      - name: ehail_fee
        data_type: numeric
        description: ""

      - name: improvement_surcharge
        data_type: numeric
        description: ""

      - name: total_amount
        data_type: numeric
        description: ""

      - name: payment_type
        data_type: int64
        description: ""
        tests:
          - accepted_values:
              values: "{{ var('payment_type_values') }}"
              severity: warn
              quote: false # so that the values inside array won't be interpreted as a string

      - name: payment_type_description
        data_type: string
        description: ""
